name: Push Tagged Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read 
      packages: write

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Setup buildx for cross platform build
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Confirm tag name
        run: echo "Tag name ${{ github.ref_name }}"
      -
        name: Build the open-cv Docker image
        run: docker buildx build --platform linux/arm/v7 open-cv --file open-cv/Dockerfile --tag ghcr.io/msaunby/pi-opencv-test:latest --push
      